const express = require("express");
const cors = require("cors");

const app = express();

app.use(cors());
app.get("/bmw", function (req, res) {
  res.json([
    { model_name: "1 Series", model_make_id: "bmw" },
    { model_name: "116", model_make_id: "bmw" },
    { model_name: "118", model_make_id: "bmw" },
    { model_name: "120", model_make_id: "bmw" },
    { model_name: "123", model_make_id: "bmw" },
    { model_name: "125", model_make_id: "bmw" },
    { model_name: "128", model_make_id: "bmw" },
    { model_name: "130", model_make_id: "bmw" },
    { model_name: "135", model_make_id: "bmw" },
    { model_name: "1500", model_make_id: "bmw" },
    { model_name: "1502", model_make_id: "bmw" },
    { model_name: "1600", model_make_id: "bmw" },
    { model_name: "1602", model_make_id: "bmw" },
    { model_name: "1800", model_make_id: "bmw" },
    { model_name: "2 Series", model_make_id: "BMW" },
    { model_name: "2.8", model_make_id: "bmw" },
    { model_name: "2000", model_make_id: "bmw" },
    { model_name: "2002", model_make_id: "bmw" },
    { model_name: "2004", model_make_id: "bmw" },
    { model_name: "2800", model_make_id: "bmw" },
    { model_name: "3", model_make_id: "bmw" },
    { model_name: "3 Series", model_make_id: "bmw" },
    { model_name: "3 Series Gran Turismo", model_make_id: "BMW" },
    { model_name: "3.3", model_make_id: "bmw" },
    { model_name: "315", model_make_id: "bmw" },
    { model_name: "316", model_make_id: "bmw" },
    { model_name: "317", model_make_id: "bmw" },
    { model_name: "318", model_make_id: "bmw" },
    { model_name: "320", model_make_id: "bmw" },
    { model_name: "3200 CS", model_make_id: "bmw" },
    { model_name: "323", model_make_id: "bmw" },
    { model_name: "324", model_make_id: "bmw" },
    { model_name: "325", model_make_id: "bmw" },
    { model_name: "328", model_make_id: "bmw" },
    { model_name: "330", model_make_id: "bmw" },
    { model_name: "332", model_make_id: "bmw" },
    { model_name: "333", model_make_id: "bmw" },
    { model_name: "335", model_make_id: "bmw" },
    { model_name: "340", model_make_id: "bmw" },
    { model_name: "4 Series", model_make_id: "BMW" },
    { model_name: "4 Series Gran Coupe", model_make_id: "BMW" },
    { model_name: "5 Series", model_make_id: "bmw" },
    { model_name: "5 Series Gran Turismo", model_make_id: "BMW" },
    { model_name: "5.8", model_make_id: "bmw" },
    { model_name: "501", model_make_id: "bmw" },
    { model_name: "502", model_make_id: "bmw" },
    { model_name: "503", model_make_id: "bmw" },
    { model_name: "507", model_make_id: "bmw" },
    { model_name: "518", model_make_id: "bmw" },
    { model_name: "520", model_make_id: "bmw" },
    { model_name: "523", model_make_id: "bmw" },
    { model_name: "524", model_make_id: "bmw" },
    { model_name: "525", model_make_id: "bmw" },
    { model_name: "528", model_make_id: "bmw" },
    { model_name: "529", model_make_id: "bmw" },
    { model_name: "530", model_make_id: "bmw" },
    { model_name: "535", model_make_id: "bmw" },
    { model_name: "538", model_make_id: "bmw" },
    { model_name: "540", model_make_id: "bmw" },
    { model_name: "545", model_make_id: "bmw" },
    { model_name: "550", model_make_id: "bmw" },
    { model_name: "6 series", model_make_id: "bmw" },
    { model_name: "6 Series Gran Coupe", model_make_id: "BMW" },
    { model_name: "600", model_make_id: "bmw" },
    { model_name: "628", model_make_id: "bmw" },
    { model_name: "630", model_make_id: "bmw" },
    { model_name: "633", model_make_id: "bmw" },
    { model_name: "635", model_make_id: "bmw" },
    { model_name: "640", model_make_id: "bmw" },
    { model_name: "645", model_make_id: "bmw" },
    { model_name: "650", model_make_id: "bmw" },
    { model_name: "7 Series", model_make_id: "bmw" },
    { model_name: "700", model_make_id: "bmw" },
    { model_name: "725", model_make_id: "bmw" },
    { model_name: "728", model_make_id: "bmw" },
    { model_name: "729", model_make_id: "bmw" },
    { model_name: "730", model_make_id: "bmw" },
    { model_name: "732", model_make_id: "bmw" },
    { model_name: "735", model_make_id: "bmw" },
    { model_name: "740", model_make_id: "bmw" },
    { model_name: "745", model_make_id: "bmw" },
    { model_name: "748", model_make_id: "bmw" },
    { model_name: "750", model_make_id: "bmw" },
    { model_name: "760", model_make_id: "bmw" },
    { model_name: "840", model_make_id: "bmw" },
    { model_name: "845", model_make_id: "bmw" },
    { model_name: "850", model_make_id: "bmw" },
    { model_name: "854", model_make_id: "bmw" },
    { model_name: "856", model_make_id: "bmw" },
    { model_name: "ActiveHybrid 3", model_make_id: "bmw" },
    { model_name: "ActiveHybrid 5", model_make_id: "bmw" },
    { model_name: "ActiveHybrid 7", model_make_id: "bmw" },
    { model_name: "Alpina", model_make_id: "bmw" },
    { model_name: "ALPINA B6 Gran Coupe", model_make_id: "BMW" },
    { model_name: "ALPINA B7", model_make_id: "BMW" },
    { model_name: "B7", model_make_id: "bmw" },
    { model_name: "Breyton", model_make_id: "bmw" },
    { model_name: "CLS", model_make_id: "bmw" },
    { model_name: "Compact", model_make_id: "bmw" },
    { model_name: "Convertible", model_make_id: "bmw" },
    { model_name: "Coupe", model_make_id: "bmw" },
    { model_name: "Dinan", model_make_id: "bmw" },
    { model_name: "Formula FB02", model_make_id: "bmw" },
    { model_name: "Formula One", model_make_id: "bmw" },
    { model_name: "FW 27", model_make_id: "bmw" },
    { model_name: "Isetta", model_make_id: "bmw" },
    { model_name: "Just 4", model_make_id: "bmw" },
    { model_name: "Karmann Asso di Quadri", model_make_id: "bmw" },
    { model_name: "L7", model_make_id: "bmw" },
    { model_name: "LMR", model_make_id: "bmw" },
    { model_name: "M", model_make_id: "bmw" },
    { model_name: "M1", model_make_id: "bmw" },
    { model_name: "M12", model_make_id: "bmw" },
    { model_name: "M28i", model_make_id: "bmw" },
    { model_name: "M3", model_make_id: "bmw" },
    { model_name: "M4", model_make_id: "BMW" },
    { model_name: "M5", model_make_id: "bmw" },
    { model_name: "M6", model_make_id: "bmw" },
    { model_name: "M6 Gran Coupe", model_make_id: "BMW" },
    { model_name: "Mini ACV 30", model_make_id: "bmw" },
    { model_name: "MM Roadster", model_make_id: "bmw" },
    { model_name: "Pickster", model_make_id: "bmw" },
    { model_name: "S3", model_make_id: "bmw" },
    { model_name: "Touring", model_make_id: "bmw" },
    { model_name: "Turbo", model_make_id: "bmw" },
    { model_name: "V12", model_make_id: "bmw" },
    { model_name: "Veritas Rennsportwagen", model_make_id: "bmw" },
    { model_name: "X Activity", model_make_id: "bmw" },
    { model_name: "X Coupe", model_make_id: "bmw" },
    { model_name: "X1", model_make_id: "bmw" },
    { model_name: "X3", model_make_id: "bmw" },
    { model_name: "X4", model_make_id: "BMW" },
    { model_name: "X5", model_make_id: "bmw" },
    { model_name: "X5 M", model_make_id: "bmw" },
    { model_name: "X6", model_make_id: "bmw" },
    { model_name: "X6 M", model_make_id: "bmw" },
    { model_name: "Z1", model_make_id: "bmw" },
    { model_name: "Z18", model_make_id: "bmw" },
    { model_name: "Z22", model_make_id: "bmw" },
    { model_name: "Z3", model_make_id: "bmw" },
    { model_name: "Z4", model_make_id: "bmw" },
    { model_name: "Z8", model_make_id: "bmw" },
    { model_name: "Z9", model_make_id: "bmw" },
    { model_name: "Z9 Gran Turismo Convertible", model_make_id: "bmw" },
  ]);
});

app.get("/jaguar", function (req, res) {
  res.json([
    { model_name: "220", model_make_id: "jaguar" },
    { model_name: "240", model_make_id: "jaguar" },
    { model_name: "3.8", model_make_id: "jaguar" },
    { model_name: "420G", model_make_id: "jaguar" },
    { model_name: "C-Type", model_make_id: "jaguar" },
    { model_name: "Concept Eight", model_make_id: "jaguar" },
    { model_name: "E Type", model_make_id: "jaguar" },
    { model_name: "E-Type", model_make_id: "jaguar" },
    { model_name: "F-Type", model_make_id: "jaguar" },
    { model_name: "Kensington", model_make_id: "jaguar" },
    { model_name: "Mark IV", model_make_id: "jaguar" },
    { model_name: "MK 10", model_make_id: "jaguar" },
    { model_name: "MK II", model_make_id: "jaguar" },
    { model_name: "MK IV", model_make_id: "jaguar" },
    { model_name: "MK IX", model_make_id: "jaguar" },
    { model_name: "MK V", model_make_id: "jaguar" },
    { model_name: "MK VII", model_make_id: "jaguar" },
    { model_name: "MK VIII", model_make_id: "jaguar" },
    { model_name: "MK X", model_make_id: "jaguar" },
    { model_name: "R Coupe", model_make_id: "jaguar" },
    { model_name: "R-D6", model_make_id: "jaguar" },
    { model_name: "S-Type", model_make_id: "jaguar" },
    { model_name: "Sovereign", model_make_id: "jaguar" },
    { model_name: "SS", model_make_id: "jaguar" },
    { model_name: "Type E", model_make_id: "jaguar" },
    { model_name: "Type S", model_make_id: "jaguar" },
    { model_name: "Type-C", model_make_id: "jaguar" },
    { model_name: "Vanden Plas", model_make_id: "jaguar" },
    { model_name: "X-300", model_make_id: "jaguar" },
    { model_name: "X-Type", model_make_id: "jaguar" },
    { model_name: "X400", model_make_id: "jaguar" },
    { model_name: "XF", model_make_id: "jaguar" },
    { model_name: "XJ", model_make_id: "jaguar" },
    { model_name: "XJ-13", model_make_id: "jaguar" },
    { model_name: "XJ220", model_make_id: "jaguar" },
    { model_name: "XJ6", model_make_id: "jaguar" },
    { model_name: "XJ8", model_make_id: "jaguar" },
    { model_name: "XJR", model_make_id: "jaguar" },
    { model_name: "XJR-11", model_make_id: "jaguar" },
    { model_name: "XJR-15", model_make_id: "jaguar" },
    { model_name: "XJS", model_make_id: "jaguar" },
    { model_name: "XK", model_make_id: "jaguar" },
    { model_name: "XK8", model_make_id: "jaguar" },
    { model_name: "XKA", model_make_id: "jaguar" },
    { model_name: "XKR", model_make_id: "jaguar" },
    { model_name: "XS", model_make_id: "Jaguar" },
  ]);
});

app.get("/ferrari", function (req, res) {
  res.json([
    { model_name: "125", model_make_id: "ferrari" },
    { model_name: "125 F1", model_make_id: "ferrari" },
    { model_name: "125S", model_make_id: "ferrari" },
    { model_name: "126", model_make_id: "ferrari" },
    { model_name: "156", model_make_id: "ferrari" },
    { model_name: "158", model_make_id: "ferrari" },
    { model_name: "159S", model_make_id: "ferrari" },
    { model_name: "166", model_make_id: "ferrari" },
    { model_name: "195", model_make_id: "ferrari" },
    { model_name: "196", model_make_id: "ferrari" },
    { model_name: "206", model_make_id: "ferrari" },
    { model_name: "208", model_make_id: "ferrari" },
    { model_name: "212", model_make_id: "ferrari" },
    { model_name: "225", model_make_id: "ferrari" },
    { model_name: "246", model_make_id: "ferrari" },
    { model_name: "250", model_make_id: "ferrari" },
    { model_name: "250 GT", model_make_id: "ferrari" },
    { model_name: "250 GTE", model_make_id: "ferrari" },
    { model_name: "250 GTO", model_make_id: "ferrari" },
    { model_name: "250 LM", model_make_id: "ferrari" },
    { model_name: "250 Mille Miglia", model_make_id: "ferrari" },
    { model_name: "250 Testarossa", model_make_id: "ferrari" },
    { model_name: "255 S", model_make_id: "ferrari" },
    { model_name: "256 F1", model_make_id: "ferrari" },
    { model_name: "275", model_make_id: "ferrari" },
    { model_name: "288 GTO", model_make_id: "ferrari" },
    { model_name: "306", model_make_id: "ferrari" },
    { model_name: "308", model_make_id: "ferrari" },
    { model_name: "312", model_make_id: "ferrari" },
    { model_name: "328 GTB", model_make_id: "ferrari" },
    { model_name: "328 GTS", model_make_id: "ferrari" },
    { model_name: "330", model_make_id: "ferrari" },
    { model_name: "330GT", model_make_id: "ferrari" },
    { model_name: "340 America", model_make_id: "ferrari" },
    { model_name: "340 F1", model_make_id: "ferrari" },
    { model_name: "340 Mexico", model_make_id: "ferrari" },
    { model_name: "340 MM", model_make_id: "ferrari" },
    { model_name: "340 Spider", model_make_id: "ferrari" },
    { model_name: "342 America", model_make_id: "ferrari" },
    { model_name: "348", model_make_id: "ferrari" },
    { model_name: "348 TS Targa", model_make_id: "ferrari" },
    { model_name: "355 Spider", model_make_id: "ferrari" },
    { model_name: "355 TS", model_make_id: "ferrari" },
    { model_name: "360", model_make_id: "ferrari" },
    { model_name: "365 BB", model_make_id: "ferrari" },
    { model_name: "365 California", model_make_id: "ferrari" },
    { model_name: "365 GT", model_make_id: "ferrari" },
    { model_name: "365 GT4", model_make_id: "ferrari" },
    { model_name: "365 GTB", model_make_id: "ferrari" },
    { model_name: "365 GTC", model_make_id: "ferrari" },
    { model_name: "365 GTC 4", model_make_id: "ferrari" },
    { model_name: "365 GTS", model_make_id: "ferrari" },
    { model_name: "375 America", model_make_id: "ferrari" },
    { model_name: "375 Indy", model_make_id: "ferrari" },
    { model_name: "375 Mille Miglia", model_make_id: "ferrari" },
    { model_name: "3Z", model_make_id: "ferrari" },
    { model_name: "400", model_make_id: "ferrari" },
    { model_name: "400 Superamerica", model_make_id: "ferrari" },
    { model_name: "410 Superamerica", model_make_id: "ferrari" },
    { model_name: "412 GT", model_make_id: "ferrari" },
    { model_name: "412 MI", model_make_id: "ferrari" },
    { model_name: "412 T2", model_make_id: "ferrari" },
    { model_name: "456", model_make_id: "ferrari" },
    { model_name: "456M", model_make_id: "ferrari" },
    { model_name: "458", model_make_id: "ferrari" },
    { model_name: "458 Italia", model_make_id: "ferrari" },
    { model_name: "500 F2", model_make_id: "ferrari" },
    { model_name: "500 Mondial", model_make_id: "ferrari" },
    { model_name: "500 Superfast", model_make_id: "ferrari" },
    { model_name: "500 Testarossa", model_make_id: "ferrari" },
    { model_name: "512 BB", model_make_id: "ferrari" },
    { model_name: "512 BBi", model_make_id: "ferrari" },
    { model_name: "512 BBi Turbo", model_make_id: "ferrari" },
    { model_name: "512 F1", model_make_id: "ferrari" },
    { model_name: "512 M", model_make_id: "ferrari" },
    { model_name: "512 S", model_make_id: "ferrari" },
    { model_name: "512 TR", model_make_id: "ferrari" },
    { model_name: "550", model_make_id: "ferrari" },
    { model_name: "553 F1", model_make_id: "ferrari" },
    { model_name: "553 F2", model_make_id: "ferrari" },
    { model_name: "575 Superamerica", model_make_id: "ferrari" },
    { model_name: "575M Maranello", model_make_id: "ferrari" },
    { model_name: "599", model_make_id: "ferrari" },
    { model_name: "599 GTB Fiorano", model_make_id: "ferrari" },
    { model_name: "612", model_make_id: "ferrari" },
    { model_name: "612 Scaglietti", model_make_id: "ferrari" },
    { model_name: "625 F1", model_make_id: "ferrari" },
    { model_name: "735", model_make_id: "ferrari" },
    { model_name: "750", model_make_id: "ferrari" },
    { model_name: "801 F1", model_make_id: "ferrari" },
    { model_name: "850", model_make_id: "ferrari" },
    { model_name: "C62", model_make_id: "ferrari" },
    { model_name: "California", model_make_id: "ferrari" },
    { model_name: "D 50", model_make_id: "ferrari" },
    { model_name: "Dino", model_make_id: "ferrari" },
    { model_name: "Enzo", model_make_id: "ferrari" },
    { model_name: "F 2005", model_make_id: "ferrari" },
    { model_name: "F1 156", model_make_id: "ferrari" },
    { model_name: "F1 2000", model_make_id: "ferrari" },
    { model_name: "F1 86", model_make_id: "ferrari" },
    { model_name: "F1 88", model_make_id: "ferrari" },
    { model_name: "F1 89", model_make_id: "ferrari" },
    { model_name: "F1 90", model_make_id: "ferrari" },
    { model_name: "F1 93", model_make_id: "ferrari" },
    { model_name: "F310", model_make_id: "ferrari" },
    { model_name: "F333", model_make_id: "ferrari" },
    { model_name: "F355", model_make_id: "ferrari" },
    { model_name: "F399", model_make_id: "ferrari" },
    { model_name: "F40", model_make_id: "ferrari" },
    { model_name: "F430", model_make_id: "ferrari" },
    { model_name: "F50", model_make_id: "ferrari" },
    { model_name: "F512 M", model_make_id: "ferrari" },
    { model_name: "F55", model_make_id: "ferrari" },
    { model_name: "F550", model_make_id: "ferrari" },
    { model_name: "FF", model_make_id: "ferrari" },
    { model_name: "FF HELE", model_make_id: "ferrari" },
    { model_name: "GTO", model_make_id: "ferrari" },
    { model_name: "KS 360 Modena", model_make_id: "ferrari" },
    { model_name: "Maranello", model_make_id: "ferrari" },
    { model_name: "Mondial", model_make_id: "ferrari" },
    { model_name: "Mythos", model_make_id: "ferrari" },
    { model_name: "P2", model_make_id: "ferrari" },
    { model_name: "P5", model_make_id: "ferrari" },
    { model_name: "Pinin", model_make_id: "ferrari" },
    { model_name: "Rossa", model_make_id: "ferrari" },
    { model_name: "Superamerica", model_make_id: "ferrari" },
    { model_name: "Testarossa", model_make_id: "ferrari" },
  ]);
});

const PORT = 7000;
app.listen(PORT, function () {
  console.log(`Server is running on port ${PORT}`);
});
